# Generated by Django 5.0.1 on 2024-01-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('deptName', models.CharField(max_length=100)),
                ('deptHead', models.CharField(max_length=50)),
                ('empCount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fullName', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
